Repository PoCInnovation/CryptoPilot-Builder, pull requests merged in 2025-06, with the labels that each got.

#22 [ADD] temporary mcp implementation
  .gitignore
  crypto-pilot-builder/python/README.md
  crypto-pilot-builder/python/chatbot.py
  crypto-pilot-builder/python/mcp_api_server.py
  crypto-pilot-builder/python/requirements.txt
Labels: enhancement

#23 [ADD] real mcp server and client implementation (w/o tools)
  crypto-pilot-builder/python/README.md
  crypto-pilot-builder/python/mcp_api_server.py
  crypto-pilot-builder/python/mcp_client/api_routes.py
  crypto-pilot-builder/python/mcp_client/config.py
  crypto-pilot-builder/python/mcp_client/mcp_client.py
  crypto-pilot-builder/python/mcp_client/mcp_http_bridge.py
  crypto-pilot-builder/python/mcp_client/session_manager.py
  crypto-pilot-builder/python/mcp_serveur/mcp_server_sdk.py
Labels: enhancement

#26 Feature/mcp implementation
  .gitignore
  crypto-pilot-builder/python/mcp_client/api_routes.py
  crypto-pilot-builder/python/mcp_client/config.py
  crypto-pilot-builder/python/mcp_client/mcp_client.py
  crypto-pilot-builder/python/mcp_client/mcp_http_bridge.py
  crypto-pilot-builder/python/mcp_client/session_manager.py
  crypto-pilot-builder/python/mcp_serveur/crypto_tools.py
  crypto-pilot-builder/python/mcp_serveur/mcp_server_sdk.py
Labels: enhancement

#31 [ADD] uv script to run mcp faster
  crypto-pilot-builder/package-lock.json
  crypto-pilot-builder/python/README.md
  crypto-pilot-builder/python/run_mcp.sh
Labels: enhancement

#35 [FIX] front in module ia and prompte
  crypto-pilot-builder/src/agent_building/Ai.vue
  crypto-pilot-builder/src/agent_building/Module.vue
  crypto-pilot-builder/src/agent_building/Progress_bar.vue
  crypto-pilot-builder/src/agent_building/Prompte.vue
Labels: bug

#36 [ADD] Updating the Readme
  README.md
Labels: documentation
